name: column-layout

services:
  frontend-empty:
    build:
      context: ./docs/demo-empty
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docs/demo-empty:/usr/share/nginx/html
    restart: always
    container_name: column-layout-frontend-empty
  frontend-content:
    build:
      context: ./docs/demo-content
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./docs/demo-content:/usr/share/nginx/html
    restart: always
    container_name: column-layout-frontend-content